theme:
  name: material
  features:
    - navigation.sections # sections are included in the left
    - toc.integrate # table of contents  is integrated on the left side
    - header-autohide # header disappears when scrolling down
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_name: xpektra
site_description: The documentation for xpektra software package
site_author: Mohit Pundir

extra_javascript:
  # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - "_static/custom_css.css"

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "Â¤" # Adds a clickable permalink to each section heading
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - autorefs
  - include_exclude_files:
      include:
        - ".htaccess"
      exclude:
        - "_overrides"
        - "assets/*.svg"
  - mkdocstrings:
      handlers:
        python:
          options:
            force_inspection: true
            heading_level: 4
            inherited_members: true
            members_order: source
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - ipynb
nav:
  - "index.md"
  - "basics.md"
  - "extensibility.md"
  - Tutorials:
      - Elasticity:
          - Fourier-Galerkin:
              - "examples/linear_elasticity.ipynb"
              - "examples/gent.ipynb"
              - "examples/j2_plasticity.ipynb"
              - "examples/multiphase_material.ipynb"
              - "examples/differential_operator.ipynb"
          - Moulinec-Suquet:
              - "examples/moulinec_suquet.ipynb"
              - "examples/moulinec_suquet_newton_krylov.ipynb"
          - Displacement-based FFT:
              - "examples/displacement_based_fft.ipynb"
      - "examples/phasefield_localization_1D.ipynb"
      - "examples/computational_homogenization.ipynb"
      - "examples/multiscale.ipynb"
  - Basic API:
      - "api/projection_operators.md"
      - "api/scheme_api.md"
      - "api/spectral_operator_api.md"
      - "api/spectral_space_api.md"
